from django.db import models
from django.utils import timezone


class Balanco(models.Model):
    Papel                                 = models.CharField(max_length=10)
    Data_ref                              = models.DateTimeField(blank=True, null=True)
    Ativo_Total                           = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Ativo_Circulante                      = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Disponibilidades                      = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Aplic_Interf_Liq1  = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Tit_Val_Mobil           = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Relac_Interf             = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Relac_Interdep            = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Opr_Credito                     = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Opr_Arrendamento_Mercantil      = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Outros_Creditos                       = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Outros_Val_Bens                   = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Ativo_Realizavel_Longo_Prazo          = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Aplic_Interf_Liq2  = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Tit_Val_Mobil           = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Relac_Interf             = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Relac_Interdep            = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Opr_Credito                     = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Opr_Arrendamento_Mercantil      = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Outros_Creditos                       = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Outros_Val_Bens                   = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Ativo_Permanente                      = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Investimentos                         = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Imob_Uso                       = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Imob_Arrendamento              = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Intangivel                            = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Diferido                              = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Passivo_Total                         = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Passivo_Circulante                    = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Depósitos                             = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Captacoes_no_Mercado_Aberto           = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Recursos_Aceites_Emissao_Tit      = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Relac_Interf             = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Relac_Interdep            = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Obrig_Emprestimos            = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Obrig_Repasse_Pais        = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Obrig_Repasse_Exterior    = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Outras_Obrig                     = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Passivo_Exigivel_Longo_Prazo          = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Depósitos                             = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Captacoes_no_Mercado_Aberto           = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Recursos_Aceites_Emissao_Tit      = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Relac_Interdep            = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Relac_Interf             = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Obrig_Emprestimos            = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Obrig_Repasse_Pais        = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Obrig_Repasse_Exterior    = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Outras_Obrig                     = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Resultados_Exercicios_Futuros         = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Part_Acionistas_Nao_Controladores     = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Patrimonio_Liquido                    = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Capital_Social_Realizado              = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Reservas_Capital                      = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Reservas_Reavaliacao                  = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Reservas_Lucro                        = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Ajustes_Avaliacao_Patrimonial         = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    Lucros_Prejuizos_Acumulados           = models.DecimalField( max_digits=19, decimal_places=2, default=0)
    def publish(self):
        self.save()

    def __str__(self):
        return self.Papel
