# Generated by Django 2.1.5 on 2019-01-24 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Papel', models.CharField(max_length=10)),
                ('Data_ref', models.DateTimeField(blank=True, null=True)),
                ('Ativo_Total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Ativo_Circulante', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Disponibilidades', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Ativo_Realizável_Longo_Prazo', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Aplicações_Interfinanceiras_Liquidez', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Títulos_Valores_Mobiliários', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Operações_Crédito', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Operações_Arrendamento_Mercantil', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Outros_Créditos', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Outros_Valores_Bens', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Ativo_Permanente', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Investimentos', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Imobilizado_Uso', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Imobilizado_Arrendamento', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Intangível', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Diferido', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Passivo_Total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Passivo_Circulante', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Passivo_Exigível_Longo_Prazo', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Depósitos', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Captações_no_Mercado_Aberto', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Recursos_Aceites_Emissão_Títulos', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Relações_Interdependências', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Relações_Interfinanceiras', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Obrigações_por_Empréstimos', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Obrigações_por_Repasse_do_País', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Obrigações_por_Repasse_do_Exterior', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Outras_Obrigações', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Resultados_Exercícios_Futuros', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Part_Acionistas_Não_Controladores', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Patrimônio_Líquido', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Capital_Social_Realizado', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Reservas_Capital', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Reservas_Reavaliação', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Reservas_Lucro', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Ajustes_Avaliação_Patrimonial', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('Lucros_Prejuízos_Acumulados', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
